#pragma once

enum DIRECTION {DIR_LEFT, DIR_RIGHT, DIR_END};

enum OBJID { OBJ_MONSTER, OBJ_PLAYER, OBJ_ITEM, OBJ_BULLET, OBJ_NPC, OBJ_MAP, OBJ_BLOCK, OBJ_SKILL, OBJ_MONSKILL, OBJ_BUTTON, OBJ_UI, OBJ_MOUSE, OBJ_END };

enum SCENEID { SC_LOGO, SC_MENU, SC_EDIT, SC_STAGE_1, SC_STAGE_2, SC_STAGE_3, SC_STAGE_4, SC_STAGE_5, SC_STAGE_6, SC_STAGE_BOSS, SC_END };

enum MONSTERID { MON_BLUESNAIL, MON_REDSNAIL, MON_GREENMUSH, MON_DELSNAIL, MON_DELPIG, MON_NIGHTE, MON_NIGHTC };