#pragma once

enum DIRECTION {DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN ,DIR_END};

enum OBJID {OBJ_PLAYER, OBJ_BULLET, OBJ_MONSTER, OBJ_NPC, OBJ_MOUSE, OBJ_MAP, OBJ_BUTTON, OBJ_END };

enum SCENEID { SC_LOGO, SC_MENU, SC_EDIT, SC_STAGE_1, SC_STAGE_2, SC_STAGE_3, SC_STAGE_4, SC_STAGE_5, SC_STAGE_6, SC_END };

enum MONSTERID { MON_BLUESNAIL, MON_REDSNAIL, MON_GREENMUSH, MON_DELSNAIL, MON_DELPIG, MON_NIGHTE, MON_NIGHTC };